title: <p align="left"> Avery Robinson </p>


description:
  <p align="left">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/averyrobinson98/">LinkedIn</a> |
  <a href="https://github.com/averyrobinson98">GitHub</a>
  </p>
  
  <p align="justify">
  UCLA Statistics senior graduating in December 2021
  <br><br>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
