title: <p align="center"> Avery Robinson </p>
logo: "/images/IMG_7754.jpeg?raw=true"

description:
  <p align="left">
  <a href="/images/Resume_Avery_Robinson.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/averyrobinson98/">LinkedIn</a> |
  <a href="https://github.com/averyrobinson98">GitHub</a>
  </p>
  
  <p align="left">
  UCLA Statistics senior graduating in December 2021
  <br><br>
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
