title: <p align="center"> Avery Robinson </p>


description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/averyrobinson98/">LinkedIn</a> |
  <a href="https://github.com/averyrobinson98">GitHub</a>
  </p>
  
  <p align="justify">
  UCLA Statistics Graduate
  <br><br>
  Applications in Data Science
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
